[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = "default-src 'self'; base-uri 'self'; frame-ancestors 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'; form-action 'self'"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Referrer-Policy = "no-referrer"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains"
