# netlify.toml — Safe Mode Hardening
[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# Global security headers (safe, non-breaking)
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Prevent caching of the landing page (token in URL)
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store"
